repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
            container_imgs/data_uploader/\.bumpversion\.cfg|
            container_imgs/app/internal/static/.*
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            container_imgs/data_uploader/\.bumpversion\.cfg|
            container_imgs/app/internal/static/.*
          )
      - id: check-yaml
        exclude: |
          (?x)(
            container_imgs/data_uploader/\.bumpversion\.cfg|
            container_imgs/app/internal/static/.*
          )
