name: Push actions
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.get_image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - name: Configure Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Login to Fly.io Registry
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl auth docker
      - name: Extract image from dev.toml
        id: get_image
        run: |
          IMAGE=$(grep "image = " fly.io/dev.toml | sed "s/.*image = '\(.*\)'/\1/")
          if [ -z "$IMAGE" ]; then
            echo "No image found in dev.toml"
            exit 1
          fi

          if docker manifest inspect $IMAGE > /dev/null 2>&1; then
            echo "Image exists"
          else
            docker build -t $IMAGE -f container_imgs/app/Dockerfile .
            docker push $IMAGE
          fi

  deploy-seed:
    name: Deploy seed
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: pulumi/actions@v4
        with:
          work-dir: ./iac-seed/
          command: up
          stack-name: main
          comment-on-pr: true
          comment-on-summary: true
          color: always
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  deploy-envs:
    name: Deploy to ${{ matrix.environment }}
    runs-on: ubuntu-latest
    needs: deploy-seed
    strategy:
      matrix:
        environment: [dev, prod]
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.21.x"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure Fly.io
        uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: pulumi/actions@v4
        with:
          work-dir: ./iac-app/
          command: up
          stack-name: ${{ matrix.environment }}
          comment-on-pr: true
          comment-on-summary: true
          color: always
          github-token: ${{ secrets.GITHUB_TOKEN }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - name: Deploy Fly.io
        run: flyctl deploy --remote-only --config fly.io/${{ matrix.environment }}.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
