name: PR actions
on:
 pull_request:
   types: [opened, reopened, edited]
   branches:
     - main
jobs:
 preview-seed:
   name: Preview seed
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: Set up Go
       uses: actions/setup-go@v5
       with:
         go-version: "1.23.x"
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-region: ${{ secrets.AWS_REGION }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     - uses: pulumi/actions@v4
       with:
         work-dir: ./iac-seed/
         command: preview
         stack-name: main
         comment-on-pr: true
         comment-on-summary: true
         color: never
         github-token: ${{ secrets.GITHUB_TOKEN }}
       env:
         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

 preview-envs:
   name: Preview environments
   runs-on: ubuntu-latest
   strategy:
     matrix:
       environment: [dev, prod]
     max-parallel: 1
   environment: ${{ matrix.environment }}
   steps:
     - uses: actions/checkout@v4
     - name: Set up Go
       uses: actions/setup-go@v5
       with:
         go-version: "1.23.x"
     - name: Configure AWS Credentials
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-region: ${{ secrets.AWS_REGION }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
     - uses: pulumi/actions@v4
       with:
         work-dir: ./iac-app/
         command: preview
         stack-name: ${{ matrix.environment }}
         comment-on-pr: true
         comment-on-summary: true
         color: never
         github-token: ${{ secrets.GITHUB_TOKEN }}
       env:
         PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
